"use client";

/**
 * Sync Status — when the last background sync ran, when the next one is
 * due, and a button to run one now.
 *
 * Reads the same `SyncStatus` blob as the Sync Schedule card above it;
 * `loadStatus()` in SettingsView owns the fetch, so this renders whatever
 * it was handed.
 *
 * Anchor id `sync-status` matches the SettingsSidebar entry — see
 * ./README.md.
 */

import { useTranslations } from "next-intl";
import RateLimitBanner from "../RateLimitBanner";
import { fmtDate, type TimeT } from "./format";
import type { SyncStatus } from "./types";

function fmtRelative(t: TimeT, ts: number | null) {
  if (!ts) {
    return "—";
  }
  const diff = ts - Date.now();
  if (diff <= 0) {
    return t("due_now");
  }
  const h = Math.floor(diff / 3_600_000);
  const m = Math.floor((diff % 3_600_000) / 60_000);
  if (h > 24) {
    return t("in_days", { count: Math.floor(h / 24) });
  }
  if (h > 0) {
    return t("in_hours_minutes", { hours: h, minutes: m });
  }
  return t("in_minutes", { minutes: m });
}

export default function SyncStatusSection({
  status,
  syncing,
  triggerSync,
}: {
  /** null until `loadStatus()` resolves. */
  status: SyncStatus | null;
  syncing: boolean;
  triggerSync: () => void;
}) {
  const tSettings = useTranslations("settings");
  const tSections = useTranslations("settings.sections");
  const tSub = useTranslations("settings.subtitles");
  const tSyncStatus = useTranslations("settings.sync_status");
  const tTime = useTranslations("settings.time");

  return (
    <div className="settings-section" id="sync-status">
      <h2 className="settings-section-title">
        {tSections("app_store_sync_status")}
      </h2>
      <p className="settings-section-subtitle">
        {tSub("app_store_sync_status")}
      </p>

      {/* Rate-limit banner — when bulk sync is throttled, the "Sync Now"
            button bounces every click into a 429 until the cooldown lifts.
            Surface that here so users don't spam the button thinking it's
            broken. We poll-while-idle so a 429 generated by another surface
            (App Detail re-sync, scheduled background tick) still shows up
            without requiring a button click first. */}
      <RateLimitBanner category="scrape" pollWhenIdle />

      {status ? (
        <div className="settings-status-grid">
          <div className="settings-status-item">
            <div className="settings-status-label">
              {tSyncStatus("last_sync")}
            </div>
            <div className="settings-status-value">
              {fmtDate(tSettings, status.lastRun)}
            </div>
          </div>
          <div className="settings-status-item">
            <div className="settings-status-label">
              {tSyncStatus("next_auto_sync")}
            </div>
            <div className="settings-status-value">
              {status.schedule === "manual"
                ? tSyncStatus("not_scheduled")
                : fmtRelative(tTime, status.nextRun)}
            </div>
          </div>
          <div className="settings-status-item">
            <div className="settings-status-label">
              {tSyncStatus("status_label")}
            </div>
            <div
              className="settings-status-value"
              style={{
                color: status.isRunning ? "var(--orange)" : "var(--green)",
              }}
            >
              {status.isRunning ? tSyncStatus("running") : tSyncStatus("idle")}
            </div>
          </div>
        </div>
      ) : (
        <div
          style={{
            display: "flex",
            gap: 8,
            alignItems: "center",
            color: "var(--text-3)",
          }}
        >
          <span className="spinner-sm" /> {tSyncStatus("loading")}
        </div>
      )}

      <button
        className="btn btn-secondary"
        disabled={syncing || status?.isRunning}
        onClick={triggerSync}
        style={{ marginTop: 20 }}
        type="button"
      >
        {syncing ? (
          <>
            <span className="spinner" /> {tSyncStatus("syncing")}
          </>
        ) : (
          tSyncStatus("sync_now")
        )}
      </button>
    </div>
  );
}
