-- Generated by v0.1.2 code, commit 879efaeca0462846538f768cb9989ba5e00d9427. Synthetic data only.
PRAGMA foreign_keys=OFF;
CREATE TABLE accessibility_features (
    id TEXT PRIMARY KEY,
    app_id TEXT NOT NULL,
    identifier TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    icon_template TEXT,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
CREATE TABLE activity_log (
    id           TEXT    PRIMARY KEY,
    type         TEXT    NOT NULL,
    status       TEXT    NOT NULL,
    app_id       TEXT,
    app_name     TEXT,
    summary      TEXT,
    detail       TEXT,
    started_at   INTEGER NOT NULL,
    ended_at     INTEGER,
    duration_ms  INTEGER
  );
INSERT INTO "activity_log" ("id","type","status","app_id","app_name","summary","detail","started_at","ended_at","duration_ms") VALUES ('activity','import','success',NULL,NULL,'Fixture import',NULL,1781222400000,NULL,NULL);
CREATE TABLE ai_debug_log (
    id          TEXT PRIMARY KEY,
    created_at  INTEGER NOT NULL,
    app_id      TEXT,
    app_name    TEXT,
    provider    TEXT,
    model       TEXT,
    phase       TEXT,
    prompt      TEXT,
    response    TEXT,
    duration_ms INTEGER,
    error       TEXT
  );
CREATE TABLE annotations (
    id          TEXT PRIMARY KEY,
    app_id      TEXT NOT NULL,
    content     TEXT NOT NULL,
    source      TEXT NOT NULL DEFAULT 'user',
    source_name TEXT,
    visibility  TEXT NOT NULL DEFAULT 'export',
    tag         TEXT,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL,
    deleted_at  INTEGER,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
INSERT INTO "annotations" ("id","app_id","content","source","source_name","visibility","tag","created_at","updated_at","deleted_at") VALUES ('note','123456','Synthetic private note','user',NULL,'private',NULL,1781222400000,1781222400000,NULL);
CREATE TABLE app_devices (
    app_id          TEXT NOT NULL,
    device_id       TEXT NOT NULL,
    first_seen_at   INTEGER NOT NULL,
    last_seen_at    INTEGER NOT NULL,
    PRIMARY KEY (app_id, device_id),
    FOREIGN KEY (app_id)    REFERENCES apps(id)    ON DELETE CASCADE,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
  );
INSERT INTO "app_devices" ("app_id","device_id","first_seen_at","last_seen_at") VALUES ('123456','device',1781222400000,1781222400000);
CREATE TABLE app_settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );
INSERT INTO "app_settings" ("key","value") VALUES ('flag.focus.audience','self');
INSERT INTO "app_settings" ("key","value") VALUES ('flag.focus.goal.understand','true');
INSERT INTO "app_settings" ("key","value") VALUES ('ai_api_key','SYNTHETIC-SECRET-NEVER-REAL');
INSERT INTO "app_settings" ("key","value") VALUES ('flag.devopts.cfgutil_uninstall','on');
INSERT INTO "app_settings" ("key","value") VALUES ('sync_bulk_state','{"fixture":"pending-sync"}');
CREATE TABLE app_verdicts (
    id           TEXT PRIMARY KEY,
    app_id       TEXT NOT NULL,
    verdict      TEXT NOT NULL CHECK (verdict IN ('safe', 'replace', 'uninstall')),
    rationale    TEXT,
    source       TEXT NOT NULL CHECK (source IN ('user', 'imported')),
    source_name  TEXT,
    set_at       INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE,
    UNIQUE (app_id, source, source_name)
  );
CREATE TABLE apps (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    iconUrl TEXT,
    bundleId TEXT,
    developer TEXT,
    firstSeen INTEGER NOT NULL DEFAULT 0,
    lastSynced INTEGER NOT NULL,
    changeCount INTEGER NOT NULL DEFAULT 0,
    changes_acknowledged_at INTEGER NOT NULL DEFAULT 0,
    /* Epoch ms until which the "What's changed" review panel is suppressed.
       0/NULL means not snoozed. Rolls off automatically (any past value is
       treated as 0). Cleared by Mark-reviewed / Dismiss. */
    changes_snoozed_until INTEGER NOT NULL DEFAULT 0,
    currentVersion TEXT,
    versionUpdatedAt INTEGER,
    whatsNew TEXT,
    /* NULL = unknown / parser could not decide; 1 = developer declared
       privacy labels; 0 = "No Details Provided" on Apple's page. */
    hasPrivacyDetails INTEGER,
    /* Mirror of hasPrivacyDetails for Apple's accessibility nutrition labels.
       NULL = unknown; 1 = at least one feature declared; 0 = shelf absent.
       Kept hot on the apps row so dashboard/grid/stats don't need to JOIN
       into accessibility_features for every query. */
    hasAccessibilityLabels INTEGER,
    /* Pricing snapshot from the iTunes Lookup endpoint, captured on every
       sync. priceAmount is the raw decimal (0 for "Free"); priceCurrency
       is the ISO code; priceFormatted is Apple's localised display string
       which we render directly. NULL across all three = "price unknown". */
    priceAmount REAL,
    priceCurrency TEXT,
    priceFormatted TEXT,
    /* In-app purchases boolean. 1 = IAP shelf with at least one item;
       0 = scraped, no IAP shelf; NULL = unknown. */
    hasIap INTEGER,
    /* Apple App Store genre/category from iTunes Lookup. Powers the
       Compare page's "Top in same category" quick-pick. NULL on existing
       rows until the next sync fills them in. */
    genreId INTEGER,
    genreName TEXT,
    /* App Store age rating from iTunes Lookup, raw string ("4+", "13+").
       Legacy 12+/17+ strings may persist on old rows; comparisons parse
       the number rather than matching the enum. NULL = unknown. */
    ageRating TEXT
  , privacyPolicyUrl TEXT);
INSERT INTO "apps" ("id","name","url","iconUrl","bundleId","developer","firstSeen","lastSynced","changeCount","changes_acknowledged_at","changes_snoozed_until","currentVersion","versionUpdatedAt","whatsNew","hasPrivacyDetails","hasAccessibilityLabels","priceAmount","priceCurrency","priceFormatted","hasIap","genreId","genreName","ageRating","privacyPolicyUrl") VALUES ('123456','Legacy fixture','https://apps.apple.com/us/app/fixture/id123456',NULL,NULL,NULL,1781222400000,1781222400000,2,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE audit_bundle_imports (
    id                  TEXT PRIMARY KEY,
    exported_at         TEXT NOT NULL UNIQUE,
    imported_at         INTEGER NOT NULL,
    recommender_name    TEXT,
    bundle_app_version  TEXT,
    apps_total          INTEGER NOT NULL DEFAULT 0,
    apps_added          INTEGER NOT NULL DEFAULT 0,
    apps_updated        INTEGER NOT NULL DEFAULT 0,
    apps_skipped        INTEGER NOT NULL DEFAULT 0,
    annotations_added   INTEGER NOT NULL DEFAULT 0
  );
CREATE TABLE audit_log (
    id         TEXT    PRIMARY KEY,
    created_at INTEGER NOT NULL,
    action     TEXT    NOT NULL,
    actor_ip   TEXT,
    user_agent TEXT,
    detail     TEXT,
    success    INTEGER NOT NULL DEFAULT 1
  );
CREATE TABLE change_review_actions (
    id            TEXT PRIMARY KEY,
    app_id        TEXT NOT NULL,
    action        TEXT NOT NULL,
    acted_at      INTEGER NOT NULL,
    covered_count INTEGER NOT NULL DEFAULT 0,
    /* JSON array of privacy_snapshots.id values pending at action time.
       Lets the History timeline render the review row as a clickable list
       of the specific syncs covered. NULL on legacy rows. */
    covered_snapshot_ids TEXT,
    snooze_until  INTEGER,
    note          TEXT,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
INSERT INTO "change_review_actions" ("id","app_id","action","acted_at","covered_count","covered_snapshot_ids","snooze_until","note") VALUES ('review','123456','reviewed',1781222400000,0,NULL,NULL,NULL);
CREATE TABLE devices (
    id                       TEXT PRIMARY KEY,
    name                     TEXT NOT NULL,
    ecid                     TEXT,
    model                    TEXT,
    ios_version              TEXT,
    device_class             TEXT,
    created_at               INTEGER NOT NULL,
    last_synced_at           INTEGER NOT NULL,
    is_unknown_placeholder   INTEGER NOT NULL DEFAULT 0
  );
INSERT INTO "devices" ("id","name","ecid","model","ios_version","device_class","created_at","last_synced_at","is_unknown_placeholder") VALUES ('device','Fixture iPhone',NULL,NULL,NULL,NULL,1781222400000,1781222400000,0);
CREATE TABLE feature_flag_overrides (
    flag_key        TEXT    PRIMARY KEY,
    override_value  TEXT    NOT NULL,
    set_at          INTEGER NOT NULL,
    set_by          TEXT    NOT NULL DEFAULT 'user',
    previous_focus  TEXT,
    quarantined     INTEGER NOT NULL DEFAULT 0
  );
CREATE TABLE import_items (
    id              TEXT PRIMARY KEY,
    import_id       TEXT NOT NULL,
    query           TEXT NOT NULL,
    edited_query    TEXT,
    status          TEXT NOT NULL,
    app_id          TEXT,
    app_name        TEXT,
    developer       TEXT,
    url             TEXT,
    icon_url        TEXT,
    country         TEXT,
    scrape_error    TEXT,
    /* Background-queue bookkeeping for rate-limit retries. next_attempt_at
       is the epoch-ms threshold for retry; attempt_count grows the backoff. */
    next_attempt_at INTEGER,
    attempt_count   INTEGER NOT NULL DEFAULT 0, removed_app_id TEXT,
    FOREIGN KEY (import_id) REFERENCES imports(id) ON DELETE CASCADE,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE SET NULL
  );
CREATE TABLE imports (
    id            TEXT PRIMARY KEY,
    created_at    INTEGER NOT NULL,
    completed_at  INTEGER,
    source        TEXT NOT NULL,
    source_label  TEXT,
    total         INTEGER NOT NULL DEFAULT 0,
    matched       INTEGER NOT NULL DEFAULT 0,
    unmatched     INTEGER NOT NULL DEFAULT 0,
    imported      INTEGER NOT NULL DEFAULT 0
  , device_id TEXT);
CREATE TABLE manual_app_events (
    id             TEXT PRIMARY KEY,
    manual_app_id  TEXT NOT NULL,
    event_type     TEXT NOT NULL,
    occurred_at    INTEGER NOT NULL,
    detail         TEXT
  );
CREATE TABLE manual_app_policy_versions (
    id                     TEXT PRIMARY KEY,
    manual_app_id          TEXT NOT NULL,
    content_hash           TEXT NOT NULL,
    first_fetched_at       INTEGER NOT NULL,
    last_fetched_at        INTEGER NOT NULL,
    policy_url             TEXT,
    source_final_url       TEXT,
    source_title           TEXT,
    source_content_type    TEXT,
    source_origin          TEXT,
    source_word_count      INTEGER NOT NULL DEFAULT 0,
    source_text            TEXT NOT NULL
  );
CREATE TABLE manual_apps (
    id                  TEXT PRIMARY KEY,
    name                TEXT NOT NULL,
    /* One of: 'web_clip' | 'testflight' | 'own_build' | 'sideloaded'.
       No CHECK constraint — TypeScript enum is the source of truth. */
    source              TEXT NOT NULL,
    developer           TEXT,
    privacy_policy_url  TEXT,
    /* Secondary link for the source (TestFlight invite, GitHub repo).
       Nullable for web clips / sideloaded. */
    source_url          TEXT,
    notes               TEXT,
    first_seen          INTEGER NOT NULL,
    updated_at          INTEGER NOT NULL
  );
CREATE TABLE notifications (
    id             TEXT    PRIMARY KEY,
    app_id         TEXT,
    app_name       TEXT    NOT NULL,
    change_summary TEXT    NOT NULL,
    created_at     INTEGER NOT NULL,
    read           INTEGER NOT NULL DEFAULT 0,
    /* 1 when the app the notification points at is no longer the match for
       the import item that produced it (user clicked "Change match"). The
       bell UI renders stale rows with a faded strikethrough. */
    stale          INTEGER NOT NULL DEFAULT 0,
    /* Quiet-hours deferral. NULL = show now; non-null = epoch ms before
       which the bell must not surface the row. Old installs gain this via
       the ALTER TABLE migration below. */
    not_before     INTEGER
  );
CREATE TABLE privacy_categories (
    id TEXT PRIMARY KEY,
    purpose_id TEXT,
    type_id TEXT,
    identifier TEXT NOT NULL,
    title TEXT NOT NULL,
    FOREIGN KEY (purpose_id) REFERENCES privacy_purposes(id) ON DELETE CASCADE,
    FOREIGN KEY (type_id) REFERENCES privacy_types(id) ON DELETE CASCADE
  );
INSERT INTO "privacy_categories" ("id","purpose_id","type_id","identifier","title") VALUES ('category',NULL,'type','DIAGNOSTICS','Diagnostics');
CREATE TABLE privacy_data_types (
    id TEXT PRIMARY KEY,
    category_id TEXT NOT NULL,
    title TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES privacy_categories(id) ON DELETE CASCADE
  );
CREATE TABLE privacy_policy_analyses (
    app_id              TEXT PRIMARY KEY,
    policy_url          TEXT NOT NULL,
    status              TEXT NOT NULL,
    source_title        TEXT,
    source_content_type TEXT,
    source_text         TEXT,
    source_word_count   INTEGER NOT NULL DEFAULT 0,
    source_origin       TEXT,
    source_final_url    TEXT,
    content_hash        TEXT,
    analysis_mode       TEXT,
    summary_json        TEXT,
    previous_summary_json TEXT,
    previous_summary_at INTEGER,
    model               TEXT,
    error               TEXT,
    updated_at          INTEGER NOT NULL,
    /* JSON array of phase log records from the most recent regenerate run.
       Each record: { phase, note?, error?, ms, at }. Surfaced in the UI. */
    last_run_log        TEXT,
    /* Epoch ms of the most recent source-page fetch. Distinct from
       updated_at (which also moves when a summary refreshes). */
    source_fetched_at   INTEGER,
    /* JSON array of { summary, highlights[] } per-chunk notes from chunked
       summarisation. Persisted after each chunk so a failed final merge can
       skip straight to merge on retry. Keyed by content_hash — discarded if
       source text changes. */
    chunk_notes_json    TEXT,
    chunk_notes_hash    TEXT,
    /* Live-run bookkeeping. run_status is 'running' between mark-start and
       mark-end, 'idle' (or NULL) otherwise. Lets the AI Policy tab rehydrate
       the in-progress spinner after navigating away and back. */
    run_status          TEXT,
    run_started_at      INTEGER,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
CREATE TABLE privacy_policy_versions (
    id                  TEXT PRIMARY KEY,
    app_id              TEXT NOT NULL,
    content_hash        TEXT NOT NULL,
    first_fetched_at    INTEGER NOT NULL,
    last_fetched_at     INTEGER NOT NULL,
    policy_url          TEXT,
    source_final_url    TEXT,
    source_title        TEXT,
    source_content_type TEXT,
    source_origin       TEXT,
    source_word_count   INTEGER NOT NULL DEFAULT 0,
    source_text         TEXT NOT NULL,
    /* Internet Archive backup for this version, populated best-effort after
       a successful scrape (Wayback availability API or Save Page Now).
       NULL until we land a snapshot URL. */
    archive_url          TEXT,
    archive_submitted_at INTEGER,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
CREATE TABLE privacy_purposes (
    id TEXT PRIMARY KEY,
    type_id TEXT NOT NULL,
    identifier TEXT NOT NULL,
    title TEXT NOT NULL,
    FOREIGN KEY (type_id) REFERENCES privacy_types(id) ON DELETE CASCADE
  );
CREATE TABLE privacy_snapshots (
    id TEXT PRIMARY KEY,
    app_id TEXT NOT NULL,
    scraped_at INTEGER NOT NULL,
    snapshot_json TEXT NOT NULL,
    changes_detected INTEGER NOT NULL DEFAULT 0,
    changes_summary TEXT,
    /* 'live' = online App Store scrape; 'wayback' = backfill from Internet
       Archive (lib/historical-import.ts). Wayback rows never produce
       notifications or bump apps.changeCount. */
    source TEXT NOT NULL DEFAULT 'live',
    /* Wayback rows: raw web.archive.org URL the snapshot was scraped from.
       NULL for live rows. */
    wayback_snapshot_url TEXT,
    /* One of: 'scheduled' | 'manual' | 'import' | 'wayback'. NULL on legacy
       rows; UI falls back to inferring from source='wayback'. */
    triggered_by TEXT,
    /* App Store version metadata at the moment this snapshot was written,
       so the History timeline can tag each row with the user's version.
       Both NULL on legacy rows and on wayback imports without version metadata. */
    app_version TEXT,
    app_version_updated_at INTEGER,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
INSERT INTO "privacy_snapshots" ("id","app_id","scraped_at","snapshot_json","changes_detected","changes_summary","source","wayback_snapshot_url","triggered_by","app_version","app_version_updated_at") VALUES ('snapshot','123456',1781222400000,'[{"identifier":"DATA_NOT_LINKED_TO_YOU","title":"Data Not Linked to You","categories":[{"identifier":"DIAGNOSTICS","title":"Diagnostics"}]}]',0,NULL,'live',NULL,'manual',NULL,NULL);
CREATE TABLE privacy_types (
    id TEXT PRIMARY KEY,
    app_id TEXT NOT NULL,
    identifier TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT,
    FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
INSERT INTO "privacy_types" ("id","app_id","identifier","title","detail") VALUES ('type','123456','DATA_NOT_LINKED_TO_YOU','Data Not Linked to You',NULL);
CREATE TABLE related_apps_observed (
    source_app_id      TEXT NOT NULL,
    related_apple_id   TEXT NOT NULL,
    related_name       TEXT NOT NULL,
    related_developer  TEXT,
    related_icon_url   TEXT,
    related_store_url  TEXT NOT NULL,
    shelf_type         TEXT NOT NULL CHECK (shelf_type IN ('may_also_like', 'more_by_developer')),
    observed_at        INTEGER NOT NULL,
    PRIMARY KEY (source_app_id, related_apple_id, shelf_type),
    FOREIGN KEY (source_app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
CREATE TABLE shortlist_entries (
    id                      TEXT PRIMARY KEY,
    source_app_id           TEXT NOT NULL,
    candidate_apple_id      TEXT NOT NULL,
    candidate_name          TEXT NOT NULL,
    candidate_developer     TEXT,
    candidate_icon_url      TEXT,
    candidate_store_url     TEXT NOT NULL,
    candidate_bundle_id     TEXT,
    note                    TEXT,
    added_at                INTEGER NOT NULL,
    /* Comma-separated compare-view modes this entry was saved from
       ('privacy' and/or 'accessibility'). Defaults to 'privacy'. */
    mode                    TEXT NOT NULL DEFAULT 'privacy',
    FOREIGN KEY (source_app_id) REFERENCES apps(id) ON DELETE CASCADE
  );
CREATE INDEX idx_accessibility_features_app
    ON accessibility_features(app_id);
CREATE INDEX idx_activity_log_started
    ON activity_log(started_at);
CREATE INDEX idx_activity_log_type_started
    ON activity_log(type, started_at);
CREATE INDEX idx_ai_debug_log_created ON ai_debug_log(created_at);
CREATE INDEX idx_annotations_active
    ON annotations(app_id, deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_annotations_app_id ON annotations(app_id);
CREATE INDEX idx_app_devices_device ON app_devices(device_id);
CREATE INDEX idx_app_verdicts_app_id ON app_verdicts(app_id);
CREATE INDEX idx_app_verdicts_user
    ON app_verdicts(app_id, verdict) WHERE source = 'user';
CREATE INDEX idx_audit_bundle_imports_imported_at
    ON audit_bundle_imports(imported_at DESC);
CREATE INDEX idx_audit_log_created ON audit_log(created_at);
CREATE INDEX idx_change_review_actions_app_time
    ON change_review_actions(app_id, acted_at DESC);
CREATE UNIQUE INDEX idx_devices_ecid ON devices(ecid) WHERE ecid IS NOT NULL;
CREATE INDEX idx_feature_flag_overrides_quarantined
    ON feature_flag_overrides(quarantined);
CREATE INDEX idx_import_items_import ON import_items(import_id);
CREATE INDEX idx_import_items_queue ON import_items(status, next_attempt_at) WHERE status = 'queued';
CREATE INDEX idx_manual_app_events_app_time
    ON manual_app_events(manual_app_id, occurred_at DESC);
CREATE INDEX idx_manual_app_policy_versions_app
    ON manual_app_policy_versions(manual_app_id);
CREATE UNIQUE INDEX idx_manual_app_policy_versions_hash
    ON manual_app_policy_versions(manual_app_id, content_hash);
CREATE INDEX idx_manual_apps_source ON manual_apps(source);
CREATE INDEX idx_notifications_created
    ON notifications(created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(read, not_before);
CREATE INDEX idx_policy_versions_app
    ON privacy_policy_versions(app_id);
CREATE UNIQUE INDEX idx_policy_versions_app_hash
    ON privacy_policy_versions(app_id, content_hash);
CREATE INDEX idx_privacy_categories_type
    ON privacy_categories(type_id);
CREATE INDEX idx_privacy_snapshots_app_time
    ON privacy_snapshots(app_id, scraped_at DESC);
CREATE INDEX idx_privacy_snapshots_changes_app_time
    ON privacy_snapshots(changes_detected, app_id, scraped_at);
CREATE INDEX idx_privacy_types_app
    ON privacy_types(app_id);
CREATE INDEX idx_privacy_types_app_identifier
    ON privacy_types(app_id, identifier);
CREATE INDEX idx_related_apps_source
    ON related_apps_observed(source_app_id, shelf_type);
CREATE INDEX idx_shortlist_entries_added
    ON shortlist_entries(added_at DESC);
CREATE INDEX idx_shortlist_entries_source
    ON shortlist_entries(source_app_id);
CREATE UNIQUE INDEX idx_shortlist_entries_source_candidate
    ON shortlist_entries(source_app_id, candidate_apple_id);
PRAGMA foreign_keys=ON;
