//! Port of the feature-flag resolver — `lib/feature-flags.ts`'s
//! `computeFlag` / `resolveFlag` / `resolveFocusBaseline`, the context
//! builder in `lib/feature-flags-server.ts`, and the row shape of
//! `GET /api/feature-flags`.
//!
//! **The rule tables are not written here.** `flag_rules.json` beside this
//! file is generated by `core/scripts/extract-settings-cases.mjs` from
//! `lib/feature-flag-rules.ts` and `lib/feature-flag-wired.ts`, and CI fails
//! if it has drifted (`just parity-settings-cases`). 221 hard defaults, three
//! audience tables, three goal tables, six accessibility rules and seventy
//! dependency edges are exactly the kind of data a hand transcription gets
//! one entry wrong in, and the one wrong entry is the one the differ never
//! reaches because no seeded focus selects it.
//!
//! The chain, in `computeFlag`'s own numbering:
//!
//!   1. hard default;
//!   2. audience rule;
//!   3. goal rules, applied in the FIXED order monitor, cleanup, minimal —
//!      not the order the goals were stored in;
//!   4. accessibility rule;
//!   5. runtime: two desktop-only flags are forced `on` under Tauri;
//!   6. dependency: a flag whose parent does not resolve to `on` collapses
//!      to `off` — and the parent is resolved through this whole chain,
//!      recursively, INCLUDING the parent's own override;
//!   7. the flag's own override, last, so it beats the collapse.
//!
//! And around it, two things `resolveFlag` adds that `computeFlag` does not
//! know about: the kill switch (an override or default of
//! `flag.devopts.feature_flag_system.enabled` equal to `"off"` makes EVERY
//! flag its hard default — including the kill switch's own row, whose
//! `currentValue` therefore ignores the very override that tripped it), and
//! `focusValue`, which is the same resolution with only THIS flag's override
//! removed — every other override, the kill-switch state included, stays.
//!
//! Two JavaScript facts the port has to reproduce rather than tidy away:
//! `override_value` is an unchecked cast, so a stored `"banana"` is echoed
//! verbatim and still fails the parent's `!== "on"` test; and
//! `AUDIENCE_RULES[audience]` on an audience that is not one of the three
//! throws (`undefined[key]`) and the route answers 500 — unless the stored
//! audience happens to name an `Object.prototype` property, in which case
//! the lookup finds a function, indexes it, gets `undefined`, and no
//! audience rule applies. Both are pinned by the generated fixture.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use super::settings::get_setting_with;
use crate::jsstr::js_locale_compare;

const RULES_JSON: &str = include_str!("flag_rules.json");

pub const KILL_SWITCH: &str = "flag.devopts.feature_flag_system.enabled";

/// Names every plain object has without declaring them. `AUDIENCE_RULES[x]`
/// for one of these yields a function or prototype rather than `undefined`,
/// so the rule lookup does not throw. `__proto__` is included: the accessor
/// returns `Object.prototype`, and indexing that with a flag key is
/// `undefined` like the rest.
const OBJECT_PROTOTYPE_NAMES: &[&str] = &[
    "constructor",
    "hasOwnProperty",
    "isPrototypeOf",
    "propertyIsEnumerable",
    "toLocaleString",
    "toString",
    "valueOf",
    "__proto__",
    "__defineGetter__",
    "__defineSetter__",
    "__lookupGetter__",
    "__lookupSetter__",
];

#[derive(Deserialize)]
struct RulesFile {
    /// `HARD_DEFAULTS`, in the source object's key order — which is the
    /// order `Object.keys` walks when the route builds its rows. The sort
    /// that follows is a total order over distinct keys, so this order does
    /// not reach the wire, but it is kept faithful anyway.
    hard_defaults: Map<String, Value>,
    audience_rules: Map<String, Value>,
    goal_rules: Map<String, Value>,
    accessibility_rules: Map<String, Value>,
    dependencies: Map<String, Value>,
    wired: Vec<String>,
}

pub struct FlagRules {
    file: RulesFile,
    wired: HashSet<String>,
}

impl FlagRules {
    /// `key in HARD_DEFAULTS` for the purposes of `getAllOverrides`' registry
    /// filter. `in` sees inherited names too, but an override keyed
    /// `"constructor"` can never reach a row (rows come from `Object.keys`)
    /// nor change a lookup, so the own-key test is observably identical.
    pub fn knows(&self, key: &str) -> bool {
        self.file.hard_defaults.contains_key(key)
    }

    pub fn keys(&self) -> impl Iterator<Item = &str> {
        self.file.hard_defaults.keys().map(String::as_str)
    }

    pub fn hard_default(&self, key: &str) -> &str {
        self.file
            .hard_defaults
            .get(key)
            .and_then(Value::as_str)
            .expect("hard_default is only asked about registry keys")
    }

    pub fn is_wired(&self, key: &str) -> bool {
        self.wired.contains(key)
    }

    fn rule_in<'a>(table: Option<&'a Value>, key: &str) -> Option<&'a str> {
        table
            .and_then(Value::as_object)
            .and_then(|m| m.get(key))
            .and_then(Value::as_str)
    }

    fn goal_rule(&self, goal: &str, key: &str) -> Option<&str> {
        Self::rule_in(self.file.goal_rules.get(goal), key)
    }

    fn accessibility_rule(&self, key: &str) -> Option<&str> {
        self.file
            .accessibility_rules
            .get(key)
            .and_then(Value::as_str)
    }

    fn parent_of(&self, key: &str) -> Option<&str> {
        self.file.dependencies.get(key).and_then(Value::as_str)
    }
}

/// The tables, parsed once. The JSON is generated and checked in, so a parse
/// failure is a build-input problem and panicking on first use is right.
pub fn rules() -> &'static FlagRules {
    static RULES: OnceLock<FlagRules> = OnceLock::new();
    RULES.get_or_init(|| {
        let file: RulesFile =
            serde_json::from_str(RULES_JSON).expect("flag_rules.json is generated and valid");
        let wired = file.wired.iter().cloned().collect();
        FlagRules { file, wired }
    })
}

/// `FocusState.goals` after `activeGoalsFrom`: `minimal` suppresses the
/// two goal tiles; `accessibility` is independent of all three.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Goals {
    pub monitor: bool,
    pub cleanup: bool,
    pub minimal: bool,
    pub accessibility: bool,
}

impl Goals {
    /// Port of `activeGoalsFrom` — see `routes_focus.rs` for the same rule
    /// applied to the `/api/focus` body.
    pub fn from_stored(monitor: bool, cleanup: bool, minimal: bool, accessibility: bool) -> Self {
        Goals {
            monitor: !minimal && monitor,
            cleanup: !minimal && cleanup,
            minimal,
            accessibility,
        }
    }
}

/// `ResolverContext`, minus `aiConfigured` (read by the focus route, never
/// by the resolver).
#[derive(Clone, Debug)]
pub struct Context {
    pub audience: String,
    pub goals: Goals,
    /// Registry-known, non-quarantined overrides. Values are whatever the
    /// row holds — see the module docs on the unchecked cast.
    pub overrides: HashMap<String, String>,
    /// Computed ONCE from the overrides above; `focus_value` keeps it even
    /// when it strips the kill switch's own override.
    pub kill_switch_off: bool,
    pub runtime_desktop: bool,
}

impl Context {
    /// `getResolverContextFromDb` given its inputs: applies `activeGoalsFrom`,
    /// the registry filter on overrides, and the kill-switch test.
    pub fn new(
        audience: &str,
        goals: Goals,
        runtime_desktop: bool,
        raw_overrides: impl IntoIterator<Item = (String, String)>,
    ) -> Self {
        let rules = rules();
        let overrides: HashMap<String, String> = raw_overrides
            .into_iter()
            .filter(|(k, _)| rules.knows(k))
            .collect();
        let kill_switch_off = overrides
            .get(KILL_SWITCH)
            .map(String::as_str)
            .unwrap_or_else(|| rules.hard_default(KILL_SWITCH))
            == "off";
        Context {
            audience: audience.to_string(),
            goals,
            overrides,
            kill_switch_off,
            runtime_desktop,
        }
    }
}

/// The ways the Node resolver can throw. Each becomes the route's 500.
#[derive(Debug, PartialEq, Eq)]
pub enum ResolveError {
    /// `AUDIENCE_RULES[audience]` is `undefined` and indexing it throws.
    UnknownAudience(String),
    /// The dependency table is a DAG by registry contract; a cycle would
    /// overflow Node's stack. Refused here at a fixed depth instead.
    DependencyCycle(String),
}

/// `computeFlag` — steps 1 to 7.
fn compute_flag(key: &str, ctx: &Context, depth: usize) -> Result<String, ResolveError> {
    let rules = rules();
    if depth > 64 {
        return Err(ResolveError::DependencyCycle(key.to_string()));
    }

    // 1. Hard default.
    let mut value = rules.hard_default(key);

    // 2. Audience rule. `AUDIENCE_RULES[audience]` must exist to be
    //    indexed; an inherited Object.prototype name exists too, as a
    //    function that has no rule for any key.
    match rules.file.audience_rules.get(ctx.audience.as_str()) {
        Some(table) => {
            if let Some(rule) = FlagRules::rule_in(Some(table), key) {
                value = rule;
            }
        }
        None if OBJECT_PROTOTYPE_NAMES.contains(&ctx.audience.as_str()) => {}
        None => return Err(ResolveError::UnknownAudience(ctx.audience.clone())),
    }

    // 3. Goal rules, in a fixed order that is NOT the storage order.
    for (goal, active) in [
        ("monitor", ctx.goals.monitor),
        ("cleanup", ctx.goals.cleanup),
        ("minimal", ctx.goals.minimal),
    ] {
        if active {
            if let Some(rule) = rules.goal_rule(goal, key) {
                value = rule;
            }
        }
    }

    // 4. Accessibility modifier.
    if ctx.goals.accessibility {
        if let Some(rule) = rules.accessibility_rule(key) {
            value = rule;
        }
    }

    // 5. Runtime environment — two desktop-only affordances forced on.
    if ctx.runtime_desktop
        && (key == "flag.desktop.app_section" || key == "flag.onboarding.method.configurator")
    {
        value = "on";
    }

    // 6. Dependency — the parent goes through the WHOLE chain, override
    //    included, before the comparison.
    let mut value = value.to_string();
    if let Some(parent) = rules.parent_of(key) {
        if compute_flag(parent, ctx, depth + 1)? != "on" {
            value = "off".to_string();
        }
    }

    // 7. The flag's own override — after the collapse, so it can undo it.
    if let Some(over) = ctx.overrides.get(key) {
        value = over.clone();
    }

    Ok(value)
}

/// `resolveFlag(key, ctx)`: the kill switch short-circuits to the hard
/// default before any other layer runs.
pub fn resolve_flag(key: &str, ctx: &Context) -> Result<String, ResolveError> {
    if ctx.kill_switch_off {
        return Ok(rules().hard_default(key).to_string());
    }
    compute_flag(key, ctx, 0)
}

/// `resolveFocusBaseline(key, ctx)`: the same resolution with this one key's
/// override removed. `killSwitchOff` is copied across UNCHANGED — Node
/// spreads the context and replaces only `overrides` — so stripping the
/// kill switch's own override does not turn the engine back on.
pub fn resolve_focus_baseline(key: &str, ctx: &Context) -> Result<String, ResolveError> {
    if !ctx.overrides.contains_key(key) {
        return resolve_flag(key, ctx);
    }
    let mut stripped = ctx.clone();
    stripped.overrides.remove(key);
    resolve_flag(key, &stripped)
}

/// `surfaceOf`: the second dot-separated segment, or `"misc"`.
pub fn surface_of(key: &str) -> String {
    let parts: Vec<&str> = key.split('.').collect();
    if parts.len() >= 2 {
        parts[1].to_string()
    } else {
        "misc".to_string()
    }
}

/// One row of `GET /api/feature-flags`, fields in the route's literal order.
#[derive(Serialize, Clone, Debug, PartialEq, Eq)]
pub struct FlagRow {
    pub key: String,
    pub surface: String,
    #[serde(rename = "hardDefault")]
    pub hard_default: String,
    #[serde(rename = "currentValue")]
    pub current_value: String,
    #[serde(rename = "focusValue")]
    pub focus_value: String,
    #[serde(rename = "override")]
    pub override_value: Option<String>,
    pub wired: bool,
}

/// The route body's `flags` array: one row per registry key, sorted by
/// surface then key with `localeCompare`. Both sorts are stable and the
/// comparator is total over distinct keys, so the pre-sort order is moot.
pub fn build_rows(ctx: &Context) -> Result<Vec<FlagRow>, ResolveError> {
    let rules = rules();
    let mut rows = Vec::with_capacity(221);
    for key in rules.keys() {
        rows.push(FlagRow {
            key: key.to_string(),
            surface: surface_of(key),
            hard_default: rules.hard_default(key).to_string(),
            current_value: resolve_flag(key, ctx)?,
            focus_value: resolve_focus_baseline(key, ctx)?,
            override_value: ctx.overrides.get(key).cloned(),
            wired: rules.is_wired(key),
        });
    }
    rows.sort_by(|a, b| {
        if a.surface == b.surface {
            js_locale_compare(&a.key, &b.key)
        } else {
            js_locale_compare(&a.surface, &b.surface)
        }
    });
    Ok(rows)
}

/// `getResolverContextFromDb`, with the connection lock already held.
///
/// `getActiveFocus` reads `audience` as `getSetting(...) || "self"` — an
/// unchecked cast, so a garbage value goes straight into the lookup that
/// throws. The four goal reads have NO default in Node (`getSetting(key)`
/// returns `undefined`, which `=== "true"` is false); `""` behaves the same.
pub fn context_from_db(conn: &Connection) -> rusqlite::Result<Context> {
    let get = |key: &str, default: &str| get_setting_with(conn, key, default);

    let audience_raw = get("flag.focus.audience", "")?;
    let audience = if audience_raw.is_empty() {
        "self".to_string()
    } else {
        audience_raw
    };
    let goals = Goals::from_stored(
        get("flag.focus.goal.monitor", "")? == "true",
        get("flag.focus.goal.cleanup", "")? == "true",
        get("flag.focus.goal.minimal", "")? == "true",
        get("flag.focus.goal.accessibility", "")? == "true",
    );
    let runtime_desktop = get("runtime_environment", "")? == "desktop"
        || std::env::var("PRIVACYTRACKER_RUNTIME").as_deref() == Ok("desktop");

    let mut stmt = conn.prepare(
        "SELECT flag_key, override_value FROM feature_flag_overrides WHERE quarantined = 0",
    )?;
    let overrides = stmt
        .query_map([], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })?
        .collect::<rusqlite::Result<Vec<(String, String)>>>()?;

    Ok(Context::new(&audience, goals, runtime_desktop, overrides))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx(audience: &str, goals: Goals, overrides: &[(&str, &str)]) -> Context {
        Context::new(
            audience,
            goals,
            false,
            overrides
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string())),
        )
    }

    #[test]
    fn the_tables_loaded_with_the_expected_shape() {
        let r = rules();
        assert_eq!(r.keys().count(), 221);
        assert_eq!(r.hard_default(KILL_SWITCH), "on");
        assert!(r.knows("flag.detail.timeline.wayback_import"));
        assert!(!r.knows("flag.not.a.real.flag"));
        assert_eq!(
            r.parent_of("flag.detail.timeline.wayback_import"),
            Some("flag.detail.timeline.wayback_rows")
        );
    }

    #[test]
    fn override_beats_the_dependency_collapse_but_not_in_focus_value() {
        let parent = "flag.detail.timeline.wayback_rows";
        let child = "flag.detail.timeline.wayback_import";
        let c = ctx("self", Goals::default(), &[(parent, "off"), (child, "on")]);
        assert_eq!(resolve_flag(child, &c).unwrap(), "on");
        // With the child's override stripped, the parent's stays: collapse.
        assert_eq!(resolve_focus_baseline(child, &c).unwrap(), "off");
    }

    #[test]
    fn kill_switch_ignores_its_own_override() {
        let c = ctx("self", Goals::default(), &[(KILL_SWITCH, "off")]);
        assert!(c.kill_switch_off);
        assert_eq!(resolve_flag(KILL_SWITCH, &c).unwrap(), "on");
        // And focusValue keeps killSwitchOff even though the override that
        // set it is the one being stripped.
        assert_eq!(resolve_focus_baseline(KILL_SWITCH, &c).unwrap(), "on");
    }

    #[test]
    fn unknown_audience_is_an_error_unless_it_is_a_prototype_name() {
        let bad = ctx("banana", Goals::default(), &[]);
        assert_eq!(
            resolve_flag("flag.global.keyboard_shortcuts", &bad),
            Err(ResolveError::UnknownAudience("banana".into()))
        );
        let sneaky = ctx("constructor", Goals::default(), &[]);
        assert_eq!(
            resolve_flag("flag.global.keyboard_shortcuts", &sneaky).unwrap(),
            "on"
        );
    }

    #[test]
    fn unknown_override_keys_are_dropped_at_context_build() {
        let c = ctx("self", Goals::default(), &[("flag.not.a.real.flag", "on")]);
        assert!(c.overrides.is_empty());
    }

    #[test]
    fn surface_is_the_second_segment_or_misc() {
        assert_eq!(surface_of("flag.detail.a11y.panel"), "detail");
        assert_eq!(surface_of("flag"), "misc");
        // `"a.".split(".")` is `["a", ""]` in both languages.
        assert_eq!(surface_of("flag."), "");
    }
}
