//! Expected wire bytes are generated by executing Node, never by Rust.
use super::{analysis, grid_meta, review, routes_stats, scope::Scope, stats};
use rusqlite::Connection;
use serde_json::{json, Value};
fn apply(conn: &Connection, statements: &Value) {
    for s in statements.as_array().unwrap() {
        let params = s["params"]
            .as_array()
            .unwrap()
            .iter()
            .map(super::row::to_sql_value)
            .collect::<Vec<_>>();
        conn.execute(stats::text(&s["sql"]), rusqlite::params_from_iter(params))
            .unwrap();
    }
}
#[test]
fn database_readers_match_fixed_clock_node_oracle() {
    let fixture: Value =
        serde_json::from_str(include_str!("../../tests/fixtures/stats-cases.json")).unwrap();
    let now = stats::number(&fixture["now"]);
    for case in fixture["cases"].as_array().unwrap() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(crate::schema_sql::SCHEMA_SQL).unwrap();
        // Same intentional legacy orphan as the Node oracle.
        conn.pragma_update(None, "foreign_keys", false).unwrap();
        if case["empty"] != true {
            apply(&conn, &fixture["base"]);
        }
        apply(&conn, &case["changes"]);
        let a = &case["args"];
        let scope = Scope::from_request(&conn, a["devices"].as_str());
        let result: stats::Result<Value> = match stats::text(&case["op"]) {
            "summary" => stats::summary(&conn, &scope, now),
            "triage" => analysis::triage(&conn, &scope, now),
            "matrix" => stats::matrix(&conn),
            "radar" => stats::radar(
                &conn,
                &a["ids"]
                    .as_array()
                    .map(|ids| {
                        ids.iter()
                            .map(|s| stats::text(s).to_owned())
                            .collect::<Vec<_>>()
                    })
                    .unwrap_or_default(),
            ),
            "timeline" => stats::timeline(
                &conn,
                a["from"].as_f64().unwrap(),
                a["to"].as_f64().unwrap(),
                a["bucket"].as_str(),
                a["appId"].as_str(),
            ),
            "mismatches" => grid_meta::mismatched_apps(&conn, &scope)
                .map(|v| json!(v))
                .map_err(Into::into),
            "queue" => review::queue(&conn, &scope, a["count"] == true, now),
            "age" => analysis::age_summary(&conn),
            "changelog" => {
                let mut params = Vec::new();
                for (key, v) in a.as_object().unwrap() {
                    let (key, value) = match key.as_str() {
                        "types" => (
                            "type",
                            v.as_array()
                                .unwrap()
                                .iter()
                                .map(stats::text)
                                .collect::<Vec<_>>()
                                .join(","),
                        ),
                        "categories" => (
                            "category",
                            v.as_array()
                                .unwrap()
                                .iter()
                                .map(stats::text)
                                .collect::<Vec<_>>()
                                .join(","),
                        ),
                        "fromMs" => ("from", v.to_string()),
                        "toMs" => ("to", v.to_string()),
                        k => (
                            k,
                            v.as_str()
                                .map(str::to_owned)
                                .unwrap_or_else(|| v.to_string()),
                        ),
                    };
                    params.push((key.to_owned(), value));
                }
                analysis::universal_changelog(&conn, &params)
            }
            _ => panic!("unknown operation"),
        };
        if case["error"] == true {
            assert!(result.is_err(), "{}: expected Node's error", case["name"]);
        } else {
            assert_eq!(
                serde_json::to_string(&result.unwrap_or_else(|e| panic!("{}: {e}", case["name"])))
                    .unwrap(),
                stats::text(&case["expected"]),
                "{}",
                case["name"]
            );
        }
        let notes = stats::query(&conn, "SELECT id FROM annotations ORDER BY id", &[])
            .ok()
            .map(|rows| {
                rows.into_iter()
                    .map(|r| r["id"].clone())
                    .collect::<Vec<_>>()
            });
        assert_eq!(
            json!(notes),
            case["annotations"],
            "{}: annotation sweep",
            case["name"]
        );
    }
    for case in fixture["ratings"].as_array().unwrap() {
        assert_eq!(
            json!(analysis::rating_min_age(stats::text(&case["raw"]))),
            case["expected"],
            "rating {:?}",
            case["raw"]
        );
    }
}
#[test]
fn query_coercion_preserves_first_value_and_js_prefixes() {
    let params = vec![("count".into(), "0".into()), ("count".into(), "1".into())];
    assert_eq!(routes_stats::get(&params, "count"), Some("0"));
    // Recorded from Number.parseInt(..., 10) in Node.
    for (raw, expected) in [
        ("25abc", Some(25.0)),
        ("", None),
        ("0x10", Some(0.0)),
        ("1e3", Some(1.0)),
        ("-1", None),
        ("90000000000000000000", Some(9e19)),
        ("\u{feff}+17", Some(17.0)),
        ("\u{85}17", None),
    ] {
        assert_eq!(
            routes_stats::nonnegative_int(Some(raw)),
            expected,
            "{raw:?}"
        );
    }
}
