// Stage the notices a Rust-backend bundle must carry (Phase 6, batch 5b).
//
// The Node build ships Node's own licence inside the standalone tarball.
// This build ships compiled Rust instead, so five files travel with it:
//
//   NOTICE                our own, as the Apache-2.0 licence asks
//   LICENSE               the licence that notice refers to
//   V8-LICENSE            for the ports of V8's date parser and JSON
//                         error messages in the core (core/README.md
//                         asks for this by name)
//   THIRD-PARTY-RUST.md   every crate that can end up in the binary,
//                         generated by scripts/generate-rust-notices.mjs
//   THIRD-PARTY-OCR.md    the OCR worker, engine and model screenshot
//                         import runs in the webview; they ship in the
//                         site under public/ocr/, with this notice and
//                         their licence texts beside them as well
//
// They land in `Contents/Resources/third-party/` and the release verifier
// refuses a bundle without them, because a notice that only exists in the
// repository is not shipped with anything.
//
// Run: `pnpm stage:notices`, or through the Rust bundle's
// beforeBuildCommand. Idempotent: wipes the destination first.
import { copyFileSync, existsSync, mkdirSync, rmSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..");

/** Source in the repository, name inside the bundle. */
const NOTICES = [
  ["NOTICE", "NOTICE"],
  ["LICENSE", "LICENSE"],
  ["core/V8-LICENSE", "V8-LICENSE"],
  ["src-tauri/THIRD-PARTY-RUST.md", "THIRD-PARTY-RUST.md"],
  ["THIRD-PARTY-OCR.md", "THIRD-PARTY-OCR.md"],
];

export function stageNotices({ root = repo, into } = {}) {
  const target =
    into ?? path.join(root, "src-tauri", "resources", "third-party");
  const missing = NOTICES.filter(
    ([from]) => !existsSync(path.join(root, from))
  );
  if (missing.length > 0) {
    const names = missing.map(([from]) => from).join(", ");
    throw new Error(
      `stage-notices: missing ${names}. Run \`pnpm notices:rust\` if the crate list is what is missing.`
    );
  }

  rmSync(target, { recursive: true, force: true });
  mkdirSync(target, { recursive: true });
  let bytes = 0;
  for (const [from, name] of NOTICES) {
    const source = path.join(root, from);
    copyFileSync(source, path.join(target, name));
    bytes += statSync(source).size;
  }
  return { target, files: NOTICES.length, bytes };
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    const result = stageNotices();
    console.log(
      `stage-notices: ${result.files} files, ${(result.bytes / 1024).toFixed(1)} kB → ${path.relative(repo, result.target)}`
    );
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
