//! Differential test: replay `core/tests/fixtures/settings-cases.json`
//! through the Rust ports behind the settings reads and require the same
//! answers Node gave.
//!
//! Three functions, one fixture, generated by
//! `core/scripts/extract-settings-cases.mjs` (`just parity-settings-cases`)
//! by importing and CALLING the real Node code — `maskWebhookUrl` by lifting
//! its source text out of the route file, the other two by import. CI
//! re-runs the generator and fails if the checked-in file has drifted, so a
//! change in Node that nobody ported is caught here.
//!
//! The read-parity differ compares these routes on ONE database state; the
//! resolver alone has 221 keys × 3 audiences × 9 goal sets × overrides of
//! reachable state behind that one comparison. This file is how the rest of
//! it is held to Node.
//!
//! As in `diff_cases.rs`, comparisons are on SERIALISED strings: with
//! `preserve_order` a `serde_json::Map` is an `IndexMap`, whose `PartialEq`
//! ignores order, and key order is part of the wire contract.

use std::collections::HashMap;

use privacytracker_core::jsstr::js_locale_compare;
use privacytracker_core::server::flags::{build_rows, Context, FlagRow, Goals};
use privacytracker_core::server::layout::{
    match_dashboard_preset, presets, reconcile_layout, CALLOUT_CARDS, CANONICAL_ORDER,
    FIRST_CLASS_CARDS, PRESET_KEYS,
};
use privacytracker_core::server::webhook::mask_webhook_url;
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/settings-cases.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("fixture is valid JSON")
}

fn ser<T: serde::Serialize>(v: &T) -> String {
    serde_json::to_string(v).expect("serialisable")
}

fn report(failures: Vec<String>, what: &str) {
    assert!(
        failures.is_empty(),
        "{} {what} case(s) diverge from Node:\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

#[test]
fn webhook_masks_reproduce_byte_for_byte() {
    let f = fixture();
    let cases = f["webhook_masks"]["cases"]
        .as_array()
        .expect("webhook_masks.cases[]");
    assert!(
        cases.len() >= 50,
        "fixture looks truncated ({})",
        cases.len()
    );
    let mut failures = Vec::new();
    for case in cases {
        let input = case["input"].as_str().expect("input");
        let expected = case["expected"].as_str().expect("expected");
        let got = mask_webhook_url(input);
        if got != expected {
            failures.push(format!(
                "── maskWebhookUrl({input:?})\n   node: {expected:?}\n   rust: {got:?}"
            ));
        }
    }
    report(failures, "webhook mask");
}

#[test]
fn layout_tables_and_presets_match_the_node_source() {
    let f = fixture();
    let t = &f["layouts"]["tables"];
    let strs = |v: &Value| -> Vec<String> {
        v.as_array()
            .expect("array")
            .iter()
            .map(|s| s.as_str().expect("string").to_string())
            .collect()
    };
    assert_eq!(strs(&t["canonical_order"]), CANONICAL_ORDER.to_vec());
    assert_eq!(strs(&t["first_class_cards"]), FIRST_CLASS_CARDS.to_vec());
    assert_eq!(strs(&t["callout_cards"]), CALLOUT_CARDS.to_vec());
    assert_eq!(strs(&t["preset_keys"]), PRESET_KEYS.to_vec());

    // buildPreset is ported, not copied; the resolved presets are the check.
    let mut failures = Vec::new();
    for (key, preset) in presets() {
        let expected = ser(&t["presets"][key]);
        let got = ser(&preset);
        if got != expected {
            failures.push(format!(
                "── preset {key}\n   node: {expected}\n   rust: {got}"
            ));
        }
    }
    report(failures, "preset");
}

#[test]
fn layouts_reconcile_and_match_like_node() {
    let f = fixture();
    let cases = f["layouts"]["cases"].as_array().expect("layouts.cases[]");
    assert!(
        cases.len() >= 20,
        "fixture looks truncated ({})",
        cases.len()
    );
    let mut failures = Vec::new();
    for case in cases {
        let name = case["name"].as_str().unwrap_or("<unnamed>");
        let why = case["why"].as_str().unwrap_or("");
        let layout = reconcile_layout(&case["stored"]);
        let got = ser(&serde_json::json!({
            "layout": layout,
            "matchedPreset": match_dashboard_preset(&layout),
        }));
        let expected = ser(&case["expected"]);
        if got != expected {
            failures.push(format!(
                "── {name}\n   why: {why}\n   stored: {}\n   node: {expected}\n   rust: {got}",
                ser(&case["stored"])
            ));
        }
    }
    report(failures, "layout");
}

#[test]
fn collation_matches_node_on_every_string_the_sort_sees() {
    let f = fixture();
    let c = &f["flags"]["collation"];
    // The primary-weight table itself, as Node produced it.
    let ascii = c["ascii_order"].as_str().expect("ascii_order");
    let mut chars: Vec<char> = ascii.chars().collect();
    chars.sort_by(|a, b| js_locale_compare(&a.to_string(), &b.to_string()));
    assert_eq!(
        chars.iter().collect::<String>(),
        ascii,
        "the ASCII collation table drifted from Node's localeCompare"
    );

    for (what, list) in [
        ("keys", &c["sorted_keys"]),
        ("surfaces", &c["sorted_surfaces"]),
    ] {
        let expected: Vec<&str> = list
            .as_array()
            .expect(what)
            .iter()
            .map(|s| s.as_str().expect("string"))
            .collect();
        let mut got = expected.clone();
        got.reverse(); // start from the wrong order on purpose
        got.sort_by(|a, b| js_locale_compare(a, b));
        assert_eq!(got, expected, "sorted {what} differ from Node");
    }
}

/// Build the resolver context a fixture case describes.
fn context_of(case: &Value) -> Context {
    let g = &case["goals"];
    let flag = |k: &str| g[k].as_bool().unwrap_or(false);
    let overrides: Vec<(String, String)> = case["overrides"]
        .as_array()
        .expect("overrides[]")
        .iter()
        .map(|pair| {
            (
                pair[0].as_str().expect("key").to_string(),
                pair[1].as_str().expect("value").to_string(),
            )
        })
        .collect();
    Context::new(
        case["audience"].as_str().expect("audience"),
        Goals::from_stored(
            flag("monitor"),
            flag("cleanup"),
            flag("minimal"),
            flag("accessibility"),
        ),
        case["runtime"].as_str() == Some("desktop"),
        overrides,
    )
}

#[test]
fn flag_resolutions_reproduce_node_in_every_recorded_context() {
    let f = fixture();
    let cases = f["flags"]["cases"].as_array().expect("flags.cases[]");
    assert!(
        cases.len() >= 30,
        "fixture looks truncated ({})",
        cases.len()
    );

    let mut failures = Vec::new();
    let mut reference: Option<Vec<FlagRow>> = None;

    for case in cases {
        let name = case["name"].as_str().unwrap_or("<unnamed>");
        let why = case["why"].as_str().unwrap_or("");
        let result = build_rows(&context_of(case));

        if let Some(kind) = case["throws"].as_str() {
            if result.is_ok() {
                failures.push(format!(
                    "── {name}\n   why: {why}\n   node: throws {kind}\n   rust: resolved every flag happily"
                ));
            }
            continue;
        }
        let rows = match result {
            Ok(rows) => rows,
            Err(e) => {
                failures.push(format!("── {name}\n   why: {why}\n   rust: {e:?}"));
                continue;
            }
        };

        if let Some(expected_rows) = case.get("rows") {
            // The reference context: the full body, byte for byte.
            let expected = ser(expected_rows);
            let got = ser(&rows);
            if got != expected {
                // Find the first row that differs to keep the message legible.
                let ea = expected_rows.as_array().expect("rows[]");
                let first = rows
                    .iter()
                    .enumerate()
                    .find(|(i, r)| ea.get(*i).map(ser) != Some(ser(r)))
                    .map(|(i, r)| {
                        format!(
                            "row {i}: node {} / rust {}",
                            ea.get(i).map(ser).unwrap_or_default(),
                            ser(r)
                        )
                    })
                    .unwrap_or_else(|| "lengths differ".to_string());
                failures.push(format!("── {name} (reference)\n   why: {why}\n   {first}"));
            }
            reference = Some(rows);
            continue;
        }

        let Some(reference) = reference.as_ref() else {
            panic!("the first non-throwing case must carry full rows");
        };
        // Order is value-independent: every case must list keys in the
        // reference order.
        let keys: Vec<&str> = rows.iter().map(|r| r.key.as_str()).collect();
        let ref_keys: Vec<&str> = reference.iter().map(|r| r.key.as_str()).collect();
        if keys != ref_keys {
            failures.push(format!("── {name}\n   why: {why}\n   rows came out in a different order from the reference context"));
            continue;
        }
        // And only the recorded rows may differ from it, in only the three
        // fields that can.
        let by_key: HashMap<&str, String> =
            reference.iter().map(|r| (r.key.as_str(), ser(r))).collect();
        let delta: Vec<Value> = rows
            .iter()
            .filter(|r| by_key.get(r.key.as_str()) != Some(&ser(r)))
            .map(|r| {
                serde_json::json!({
                    "key": r.key,
                    "currentValue": r.current_value,
                    "focusValue": r.focus_value,
                    "override": r.override_value,
                })
            })
            .collect();
        let expected = ser(&case["delta"]);
        let got = ser(&delta);
        if got != expected {
            failures.push(format!(
                "── {name}\n   why: {why}\n   rows differing from the reference —\n   node: {expected}\n   rust: {got}"
            ));
        }
    }
    report(failures, "flag context");
}
