#!/usr/bin/env node
/**
 * Mechanically lift the schema DDL out of `lib/db.ts` into a verbatim Rust
 * string constant at `core/src/schema_sql.rs`.
 *
 * Why generate instead of hand-copy: the CREATE block is ~640 lines. A
 * single transcription typo would be a schema-parity failure to chase
 * down; extracting the exact bytes makes `core/` faithful to `db.ts` by
 * construction, and re-running this after any schema change keeps them in
 * lockstep. The generated file is checked in (reviewers diff it against
 * db.ts) and carries a header saying it is generated.
 *
 * This lifts ONLY the big `db.exec(`…`)` schema block — the first
 * backtick-delimited db.exec argument in the file. The guarded ALTER
 * migrations and the data backfills are hand-ported in core/src/db.rs
 * (they are short, individually reviewable, and the parity harness
 * catches any slip), because they are control flow, not a single string.
 *
 * Usage:  node core/scripts/extract-schema.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..", "..");
const dbTs = readFileSync(path.join(repo, "lib", "db.ts"), "utf8");

// The schema is the first backtick-delimited argument to db.exec(. Later
// db.exec(`…`) calls (the stale-run_status UPDATE, the policy_versions
// seed) also use backticks, so we take the FIRST opening and its matching
// close — the schema block contains no `); sequence, so a plain split is
// unambiguous.
const OPEN = "db.exec(`";
const openIdx = dbTs.indexOf(OPEN);
if (openIdx === -1) {
  console.error("extract-schema: could not find `db.exec(` in lib/db.ts");
  process.exit(1);
}
const after = dbTs.slice(openIdx + OPEN.length);
const closeIdx = after.indexOf("`);");
if (closeIdx === -1) {
  console.error(
    "extract-schema: could not find the closing `); of the schema block"
  );
  process.exit(1);
}
const schema = after.slice(0, closeIdx);

if (/\$\{/.test(schema)) {
  console.error(
    "extract-schema: the schema block contains a template interpolation — it is no longer a pure literal, refusing to emit a misleading constant"
  );
  process.exit(1);
}
// Sanity: the block must contain the tables we depend on downstream.
for (const t of [
  "apps",
  "privacy_snapshots",
  "feature_flag_overrides",
  "app_devices",
]) {
  if (!schema.includes(`CREATE TABLE IF NOT EXISTS ${t}`)) {
    console.error(
      `extract-schema: expected table \`${t}\` missing from the extracted block — extraction is wrong`
    );
    process.exit(1);
  }
}

const tableCount = (schema.match(/CREATE TABLE IF NOT EXISTS/g) ?? []).length;
const indexCount = (
  schema.match(/CREATE (?:UNIQUE )?INDEX IF NOT EXISTS/g) ?? []
).length;

// Pick a raw-string hash count that cannot collide with the SQL body.
let hashes = "#";
while (schema.includes(`"${hashes}`) || schema.includes(`${hashes}"`)) {
  hashes += "#";
}

const out = `// @generated by core/scripts/extract-schema.mjs from lib/db.ts — DO NOT EDIT.
//
// This is the byte-for-byte schema DDL block that lib/db.ts runs via a
// single db.exec(\`…\`) on every database open. Regenerate after any
// schema change:  node core/scripts/extract-schema.mjs
//
// Extracted: ${tableCount} CREATE TABLE, ${indexCount} CREATE INDEX statements.
// The guarded ALTER-TABLE migrations and the data backfills that db.ts runs
// AFTER this block are hand-ported in core/src/db.rs.

/// The full CREATE TABLE / CREATE INDEX block, verbatim from lib/db.ts.
pub const SCHEMA_SQL: &str = r${hashes}"${schema}"${hashes};
`;

const dest = path.join(repo, "core", "src", "schema_sql.rs");
writeFileSync(dest, out);
console.log(
  `extract-schema: wrote ${path.relative(repo, dest)} (${tableCount} tables, ${indexCount} indexes, ${schema.length} bytes)`
);
